[pytest]

testpaths =
    test

addopts =
    -ra
    -v

markers =
    automation: Generated automation
    positive: Positive tests
    negative: Negative tests
    validation: Validation tests
    boundary: Boundary tests
    security: Security tests